Final-touch
malikhaiderkhan/Leaderboard pull request #3
Opened 2023-07-07 21:11 UTC by malikhaiderkhan

In this part of project I implemented some css styling to look it better.

2023-07-07 21:56 UTC, franclobo requested changes
Hi @malikhaiderkhan, 

# Required Changes ♻️

![so-close-jim-halpert](https://github.com/malikhaiderkhan/Leaderboard/assets/58642949/39442a90-27ed-4cb6-b714-8ab025555141)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Use webpack ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 21:56 UTC, franclobo commented on src/style.css
> +  background-image: url('./images/lead5.png');
- [ ] Kindly review your `webpack.config.js` and add the images loader to load the images successfully on your page, you can review this [article](https://webpack.js.org/guides/asset-management/#loading-images), besides correcting the styles of your page to match with the wireframe 👇🏽 

| Wireframe | Your design |
|---|---|
| ![image](https://github.com/malikhaiderkhan/Leaderboard/assets/58642949/280b4005-668b-4cc2-93b8-78998475c699) | ![image](https://github.com/malikhaiderkhan/Leaderboard/assets/58642949/84a34656-9b21-4c8f-9978-b00362c92336) | 

- [ ] Finally, I suggest creating your own game to have a shorter score list 👇🏽 

![image](https://github.com/malikhaiderkhan/Leaderboard/assets/58642949/7c1f50e1-96a4-44b2-963d-86d4c6b6d15a)

2023-07-08 08:38 UTC, malikhaiderkhan commented on src/style.css
> +  background-image: url('./images/lead5.png');
@franclobo for creating own game I have to create new ID?

2023-07-08 10:41 UTC, malikhaiderkhan commented
- Add the image loader successfully in webpack.config.js as suggested by reviewer.
- and the other part reviewer suggest to create own game I didn't understand the point because it's also not in the project requirements and I created my own ID '2ag8QvxcyAjEtOo0qNyP' from API by following the documentation provided by Microverse. 
https://us-central1-js-capstone-backend.cloudfunctions.net/api/games/2ag8QvxcyAjEtOo0qNyP/scores/

2023-07-08 10:58 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @malikhaiderkhan ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Beautiful UI ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 11:01 UTC, merged